language: java
sudo: false
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/110a7c0daf817ba48ccc
    on_success: change
    on_failure: always
    on_start: false
jdk:
- oraclejdk8
install: true
script: ./buildViaTravis.sh
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
  - secure: FCUvpJDLz7hPmD6DXGdBQf+Kl888OVzktsChkVZKivdvJ36TSpt/xyH5hR3r2G6AdPwnRy6PSKAwvHV8d0hEiZrWmX+phaR4/3O6PE8ix1jDD1iRp6ssDDii/QW2jrT5OR3wAS8F8GSTgdjwderbm6XoFZSLFWYrpvyVqEQcS9c=
  - secure: f2j7J7XUwPIOoSr+OykHSHhhqzBdX8DKI21yHmW3ns/j91eu+TzZjWajfZjQUucTGjBF4TePSN3NjfGY+EDn53IjgXqtJrZwTOpByNWuupkwGzeoIlKcd9d6BjUIhnEpEREFKEZgLeAssAsoEdgj3cxU9qJ8t/ocLGPRMTiJsyo=
  - secure: aHYlTItG3wnShISTBKeG9IWo6+SMpYXVb50Vx70uufSFCrbMyGZrb0MqqVP5SEzB6eALdWsGiVXXOSCQUPDc/5wwAj/XV52KKZcyeDJhedliirxXbVDJAdrW/W3FSaeBL8t6G+P55yymUyR1qHy0phbjfyJzSRxL3/kaX/MXhZs=
  - secure: gewD2YDQULF80anP8Ji0VxgcinkE9RyU2ucrMyYXkJmnETryHrnLmKdWCaWfIzRqcCxu/e/mg3QjnOKgz2YtmYgkdlBljbLUqWgvRq95D56BCLwjMx0RZscHaT82JTq1uz9f5EBSSRfw8AR9yPsRWjss8P2h6yI0AuWFqmjXiag=
