name: Auto Merge Dependabot PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge-dependabot:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (required by `github-script`)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Auto-approve Dependabot PRs
        if: success()
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Manually merge Dependabot PR
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --repo "${{ github.repository }}"
